### ISSUE TITLE
Problems when updating Dates

### ISSUE THREAD

**Issue by gmrperdigao** [grahamearley/FirestoreGoogleAppsScript#75] opened 2020-03-16 20:42 UTC
Hi!
I'm using a cell value containing a date to update a document's field. It was working properly on Friday, but today the same function is updating this date as an empty map and not as a timestamp. Does someone knows what could have happened?

**Comment by Doomd** [comment] 2020-03-30 19:57
Please provide your code...

**Comment by AndresPrez** [comment] 2020-05-09 18:11
Im experiencing the same issue. My date fields are inserted as empty Maps.

**Comment by LaughDonor** [comment] 2020-05-09 18:12
@AndresPrez , could you please provide some of your code so that I can reproduce your issue?

**Comment by AndresPrez** [comment] 2020-05-09 18:18
Sure, give me a moment. But basically Im getting the "Date" Object from a google spreadsheet Date cell.

**Comment by AndresPrez** [comment] 2020-05-09 20:01
Hey @LaughDonor, I just copied all your files (from lates release `b35c224`, ``v24) into my Google Appscript project and it worked. 

My guess is that this release code might not be properly updated in Google's Libraries repo?

**Comment by LaughDonor** [comment] 2020-05-11 15:39
Right, this was fixed in 0edb5f705c3d6e4e127829c43aa94778a01e2ee6 which is scheduled for the next release.

I'll close the issue when v25 is out.

**Closed** 2020-05-11 15:44 UTC

**Comment by shoumik1** [comment] 2020-05-16 03:38
@LaughDonor I seem to be having the same issue when submitting a Date. The resulting field in the document is an empty map even when using v26.

**Comment by shoumik1** [comment] 2020-05-16 06:36
Apologies, the issue was due to using the V8 runtime. The Legacy runtime works perfectly! 
If anyone else runs into this go to Run -> Disable new Apps Script runtime powered by Chrome V8.
