### ISSUE TITLE
GAS limited date recognition depending on precision

### ISSUE THREAD

**Issue by jgassie** [grahamearley/FirestoreGoogleAppsScript#50] opened 2018-11-07 22:14 UTC
If I update/establish a date field using the Google.Cloud.Firestore.V1Beta1 (1.0.0-beta12), under C#, in the Firestore DB Console, the date field displays just fine (as valid) and as timestamp as expected.  When reading it back with the GAS library, it is not recognized as valid... displaying it back with GAS from retrieving a document shows as 'Wed Dec 31 18:00:00 GMT-06:00 1969'  even though the console displays the date as a valid timestamp type (example, '7 November 2018 at 14:14:19 UTC-6' shown in the console, not recognized properly with GAS library)... If you have any ideas, or something I may have missed, let me know, thank you!  [dates created/updated w/GAS library in my testing, no issues]
Both of the following work fine for updating the date in C#, but either way is an issue reading back with GAS library... 
`Dictionary<FieldPath, object> updates = new Dictionary<FieldPath, object>
{
  { new FieldPath("Status"), "TEST" },
  { new FieldPath("ItemNo"), spID },
  { new FieldPath("SPDate"), Timestamp.FromDateTime(dUTC) }
};

Dictionary<FieldPath, object> updates = new Dictionary<FieldPath, object>
{
  { new FieldPath("Status"), "TEST" },
  { new FieldPath("ItemNo"), spID },
  { new FieldPath("SPDate"), dUTC }
};`
Thank you,
- Jerry

**Comment by jgassie** [comment] 2018-11-08 18:20
OK well it seems I have to truncate the precision of the DateTime value in C# prior to the update... if I need to work with that value in GAS at any point that is... 
I had no problems reading back the timestamp when using the library in C#.. it was only an issue under Google Apps Script... For example, the original date displays under C# as 2018-11-07T20:14:19.488808Z ... which was not properly recognized by GAS.  I then changed the code to truncate to milliseconds, and now it is recognized as 2018-11-08T18:11:23.829Z, which GAS has no problem with...

**Comment by LaughDonor** [comment] 2020-05-04 23:11
Duplicate of #42

**Closed by LaughDonor** 2020-05-04 23:11 UTC
Labels: duplicate
