### ISSUE TITLE
Timestamp values return 'Invalid date'

### ISSUE THREAD

**Issue by marchovarela** [grahamearley/FirestoreGoogleAppsScript#41] opened 2018-07-12 21:08 UTC
Firestore [timestampValue](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/Value) field type uses a timestamp in RFC3339 UTC "Zulu" format. App Script Date object is unable to properly parse that format, resulting in an 'Invalid date'.

Maybe do a custom parsing in [FirestoreDocument.js#L92](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/master/FirestoreDocument.js#L92) before returning?

**Comment by LaughDonor** [comment] 2018-07-12 21:36
Excellent find! I verified the issue, and saw that GAS doesn't like the extra precision that Firebase gives.

**Comment by grahamearley** [comment] 2018-07-14 14:45
Thanks for reporting this! 

I'm trying to recreate the issue and not having any luck in v19. Could one of you add some code for how to recreate this? Here's my test:

```javascript
function saveAndReadDates() {
  const now = Date()
  
  const dateObj = {
    "date" : now
  }
  
  firestore.createDocument("DateTests/madeInScript", dateObj)
  
  // Read the value we created in this script, and one
  //  that I created in the Firestore console.
  const madeInScript = firestore.getDocument("DateTests/madeInScript");
  const madeInFirestore = firestore.getDocument("DateTests/madeInFirestore");
  
  Logger.log("Document made in script:");
  Logger.log(madeInScript)
  
  Logger.log("Document made in firestore:");
  Logger.log(madeInFirestore);
  
  const scriptDate = madeInScript.fields.date;
  const firestoreDate = madeInFirestore.fields.date;
  
  Logger.log("Script doc's date: " + scriptDate);
  Logger.log("Firestore doc's date: " + firestoreDate);
}
```

And here are the logs that get printed:

```
[18-07-14 09:39:32:592 CDT] Document made in script:
[18-07-14 09:39:32:593 CDT] {createTime=2018-07-14T14:39:32.489421Z, name=projects/xxxxxx/databases/(default)/documents/DateTests/madeInScript, updateTime=2018-07-14T14:39:32.489421Z, fields={date=Sat Jul 14 2018 09:39:32 GMT-0500 (CDT)}}
[18-07-14 09:39:32:593 CDT] Document made in firestore:
[18-07-14 09:39:32:594 CDT] {createTime=2018-07-14T14:36:27.721690Z, name=projects/xxxxxx/databases/(default)/documents/DateTests/madeInFirestore, updateTime=2018-07-14T14:36:27.721690Z, fields={date=Sat Jul 14 14:08:38 GMT-05:00 2018}}
[18-07-14 09:39:32:594 CDT] Script doc's date: Sat Jul 14 2018 09:39:32 GMT-0500 (CDT)
[18-07-14 09:39:32:595 CDT] Firestore doc's date: Sat Jul 14 2018 14:08:38 GMT-0500 (CDT)
```

**Comment by LaughDonor** [comment] 2018-07-14 15:51
I recreated the issue by passing the date string to `new Date ()`.

```javascript
function tester() {
  var x = new Date("2014-10-02T15:01:23.0451Z")
  var y = 0
}
```

And putting a breakpoint on the second line.


And just now I'm realizing that my fix needs a bit more work cause it doesn't get the substring from the end of the format if there are other precision levels.

**Comment by grahamearley** [comment] 2018-07-14 17:38
@LaughDonor Where did you get that Date string? Doesn't the timestamp type get parsed into a `Date` object when read from Firestore [here](https://github.com/grahamearley/FirestoreGoogleAppsScript/blob/master/FirestoreDocument.js#L92)?

When does this error occur when interacting with the library?

**Comment by LaughDonor** [comment] 2018-07-14 17:45
I clicked on the link OP posted. And that is exactly where the issue lies.

The issue would happen whenever they grab a document with a datetime in that RFC format.

**Comment by grahamearley** [comment] 2018-07-14 18:04
Okay, I see that there's an issue parsing Dates formatted that way in Google Apps Scripts. But when I add documents with timestamp fields and read them back from Firestore using the library, I see the correct date coming in. Do you have a test case for reading timestamp fields from a Firestore document where the date comes in incorrectly? 

I think I'm missing something here about how to reproduce this.

**Comment by LaughDonor** [comment] 2018-07-14 18:08
I didn't take the time to do this.. but it should theoretically be possible with an existing Database.

**Comment by LaughDonor** [comment] 2018-07-14 21:06
@grahamearley, I've updated my PR. This will cover all those edge cases that may have that value saved, if it exists.

**Comment by LaughDonor** [comment] 2018-07-14 21:14
Gah, I took another crack at reading the [Firestore Docs - Value storage](https://firebase.google.com/docs/firestore/reference/rest/v1beta1/Value#FIELDS.timestamp_value) and I read that it _**stores**_ the data and removes that extra precision internally anyway. Since that format coincides with the format which GaS parses the date string; there doesn't seem to be an issue, and I recommend this should be closed unless @marchovarela can produce an example to the contrary.

**Comment by grahamearley** [comment] 2018-07-15 02:01
Okay great! Thanks for jumping on this issue @LaughDonor. 

I'll close this for now. @marchovarela -- reply if we're missing something and should reopen.

**Closed by grahamearley** 2018-07-15 02:01 UTC
