### ISSUE TITLE
Firebase Document Call Data Type: Timestamp

### ISSUE THREAD

**Issue by BPConstruction** [grahamearley/FirestoreGoogleAppsScript#24] opened 2018-05-20 18:33 UTC
When calling for the doc fields using getDocument, the datatype "Timestamp" from firebase returns null , so theres no way of knowing what the original value was before writing it back to firebase with update document.  Let me know if there is a work around. Thanks!

**Comment by grahamearley** [comment] 2018-05-20 22:32
Currently not all Firestore datatypes are implemented. However, soon they will be! @LaughDonor has a pull request up (#20) that adds this feature, and it will be released in a new version of the library soon. 

I'm going to close this issue because it's a duplicate of #18. If you want to stay updated on the status of the timestamp implementation, subscribe to #18 or #20!

**Closed by grahamearley** 2018-05-20 22:32 UTC

**Comment by grahamearley** [comment] 2018-05-31 13:54
Hey @BPConstruction, the timestamp data type has been added! Check it out in version 16 of the library. And make sure to read the method documentation [here](https://github.com/grahamearley/FirestoreGoogleAppsScript/wiki/Firestore-Method-Documentation), as some things have changed.
